name: CD

on:
  release:
    types: [ published ]

jobs:
  publish_lib:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Build & publish to Reposilite
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: |
            clean
            build
            publish
            -Pversion=${{ github.event.release.tag_name }}
        env:
          REPOSILITE_USERNAME: ${{ secrets.REPOSILITE_USERNAME }}
          REPOSILITE_PASSWORD: ${{ secrets.REPOSILITE_PASSWORD }}